# -*- mode: ruby -*-
# vim: set ft=ruby ts=2 et :

VAGRANTFILE_API_VERSION = "2"

# Tested with Vagrant version:
Vagrant.require_version ">= 1.7.2"

BOX       = "centos/7"
CPU       = 8
MEM       = 16384
DISK      = "200G"
VM_NAME   = "antelopedb"
HOST_NAME = "antelopedb"

$provision = <<-SCRIPT
mkdir /home/vagrant/build/
sudo chown -R vagrant: build/
sudo mkfs.xfs /dev/vdb
sudo mount /dev/vdb /home/vagrant/build/
echo '/dev/vdb /home/vagrant/build xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0' | sudo tee -a /etc/fstab 
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.ssh.insert_key = false

  config.vm.define VM_NAME do |node|
    node.vm.box = BOX
    node.vm.hostname = HOST_NAME
    node.vm.provider :libvirt do |domain|
      domain.uri = 'qemu+unix:///system'
      domain.driver = 'kvm'
      domain.memory = MEM
      domain.cpus = CPU
      # https://bugzilla.redhat.com/show_bug.cgi?id=1706289
      domain.qemu_use_session = false
      domain.storage :file, :size => DISK
    end # provider
  end # define

	config.vm.provision "shell", inline: $provision
end # vagrant
